[theme]
primaryColor="#6366f1"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f4f4f5"
textColor="#09090b"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
